# environment.yml
name: ml_modelo_predictivo_estudiantil
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyter
  - notebook  # Necesario para evitar el error "no module named notebook.services"
  - xgboost
  - pip

  - pip:
    - imbalanced-learn  # Para SMOTE
    - scikit-optimize
    - shap  # Para interpretación de modelos
    - joblib
    - pytest  # Para pruebas unitarias
    - flake8  # Para linting
    - jupyter_contrib_nbextensions  # Opcional (extensiones útiles para Jupyter)
    - nbconvert  # Para exportar notebooks a HTML/PDF