# environment.yml
name: ml_modelo_predictivo_estudiantil  # Nombre del entorno
channels:
  - conda-forge  # Canal prioritario para paquetes actualizados
dependencies:
  - python=3.9  # Versión de Python (ajusta si es necesario)
  - pandas  # Manipulación de datos
  - numpy  # Operaciones numéricas
  - scikit-learn  # Modelos de ML
  - matplotlib  # Visualización
  - seaborn  # Visualización avanzada
  - jupyter  # Notebooks
  - xgboost  # Modelos de gradient boosting
  - pip  # Instalación de paquetes desde PyPI

  # Paquetes adicionales desde PyPI
  - pip:
    - imbalanced-learn  # Para técnicas de balanceo (SMOTE)
    - scikit-optimize  # Optimización bayesiana
    - shap  # Interpretación de modelos
    - joblib  # Serialización de modelos
    - pytest  # Pruebas unitarias
    - flake8  # Linter para código
    - jupyter_contrib_nbextensions  # Extensiones útiles para Jupyter