# environment.yml
name: ml_modelo_predictivo_estudiantil
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyter
  - notebook
  - xgboost
  - pip

  - pip:
    - imbalanced-learn
    - scikit-optimize
    - shap
    - joblib
    - pytest
    - flake8
    - nbconvert
    - tabulate